name: e2e

on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run e2e tests
        run: yarn test
